version: '3'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=interview1  
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    image: dcmul/solution:0.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=interview1
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - DJANGO_SETTINGS_MODULE=solution.settings
    ports:
      - "8750:80"
    depends_on:
      - db
      - redis
  redis:
    image: redis
    volumes:
      - redis:/data
volumes:  
  redis:
  db:  
