version: '3'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data  
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}            
  web:
    build: .
    image: dcmul/solution:0.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DJANGO_SETTINGS_MODULE=solution.settings
      - SG_USER=${SG_USER}
      - SG_PWD=${SG_PWD}
    ports:
      - "8150:80"
    depends_on:
      - db
      - redis
  redis:
    image: redis
    volumes:
      - redis:/data
volumes:  
  redis:
  db:  
