# Generated by Django 3.2.2 on 2021-05-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterreading',
            old_name='time',
            new_name='time_stamp',
        ),
    ]
